### ISSUE TITLE
Can't select a cell

### ISSUE THREAD

**Issue by khachuong** [Yalantis/ColorMatchTabs#16]
I tried to override didSelectRowAtIndexPath() method, but it does not work although I tried to debug it. It never called. So please so me how to detect selection a cell. Thank you very much

**Comment by serejahh** [comment]
Hi @khachuong!

It happens because we [disabled selection](https://github.com/Yalantis/ColorMatchTabs/blob/f0c5af2d5f211fe0f35d45d0a1f54f4f219856d6/Example/Example/Classes/ViewControllers/StubContentViewController.swift#L29) for the demo app. If you remove the line `tableView(tableView:, didSelectRowAtIndexPath:)` will be called
