### ISSUE TITLE
Storyboard interface as a content

### ISSUE THREAD

**Issue by jotayc** [Yalantis/ColorMatchTabs#19]
Hi, 

 I'm practicing with the example and I have a doubt if is it possible to create a interface with the storyboard and show it as content? In case that I want to create my own content and not just uitableviewController.  I tried to get the reference from the storyboard but or crash or the content is empty.

Thanks.

**Comment by serejahh** [comment]
Hi @jotayc! Thanks for your interest!

Unfortunately, it can't be done for now. I hope, you will be able to do it in version 2.0

**Comment by raypendergraph** [comment]
I am trying to do this as well. Currently what I have working is that the ColorMatchTabsViewControllerDataSource returns UIViewControllers loaded from other storyboards These controllers are loading with custom UIViewControllers. 

The problem I am running into is that I would like to refresh some information in that view with the **viewDidAppear** or **viewWillAppear** methods but these do not seem to be called when the user selects the different tabs. 

I was thinking of introducing a new protocol for custom controllers to implement so that I can tell them that they have been selected/deselected by calling the protocol somewhere within the ColorMatchTabsViewController. 

Would this work or is there a better solution?

**Comment by fusionbeam** [comment]
i see 2.0.1 is out. is this possible now?

**Comment by rnkyr** [comment]
currently, there's a bug with the transition of a content controller (#72)
