### ISSUE TITLE
How to remove center button and add them to navigation bar

### ISSUE THREAD

**Issue by akhilm3** [Yalantis/ColorMatchTabs#4]
Title explains all

**Comment by serejahh** [comment]
Hi @akhilm3! Thanks for your interest to our component! 

The component contains:
- Circle menu
- Top tabbar
- Scollable content
- View controller which aggregates three components above in one
  
  So, if you want to use exactly the same screen as on animation, use `ColorMatchTabsViewController`, otherwise you can combine other subcomponents as you want

**Comment by pit1** [comment]
;-)
